swagger: "2.0"
info:
  version: 1.0.0
  title: get-all-banks
  description: metodo para obtener todas las entidades financieras disponibles en el motor.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Banking - Exisoft
    email: abusto@exisoft.com.ar
    url: http://exisoft.com.ar
  license:
    name: Exisoft
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: api-banking.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /entidadesFinancieras:
    get:
      description: |
        Retorna todas las Entidades Financieras disponibles segun configuracion.
      operationId: findEntidadesFinancieras
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: respuesta de entidades financieras
          schema:
            type: array
            items:
              $ref: '#/definitions/EntidadFinanciera'
       
    post:
      description: Crea nuevas entidades financieras
      operationId: addEntidadFinanciera
      parameters:
        - name: entidadFinanciera
          in: body
          description: Entidad Financiera a agregar al stores
          required: true
          schema:
            $ref: '#/definitions/NewEntidadFinanciera'
      responses:
        200:
          description: Respuesta de Entidad Financiera
          schema:
            $ref: '#/definitions/EntidadFinanciera'
       
  /entidadesFinancieras/{id}:
    get:
      description: Obtiene la Entidad Financiera segun el ID enviado
      operationId: Encuentra Entidad Financiera por ID
      parameters:
        - name: id
          in: path
          description: ID de la entidad financiera a buscar
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: EF response
          schema:
            $ref: '#/definitions/EntidadFinanciera'
        
    delete:
      description: Elimina una entidad Financiera por ID
      operationId: deleteEntidadFinanciera
      parameters:
        - name: id
          in: path
          description: ID de la entidad financiera a eliminar
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: entidad financiera deleted
        
definitions:
  EntidadFinanciera:
    allOf:
      - $ref: '#/definitions/NewEntidadFinanciera'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewEntidadFinanciera:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string